# How to use try catch in JuliaLang?
// plain

Try-catch blocks are used to handle errors in JuliaLang. They are used to catch errors that occur during the execution of a program and take appropriate action.

## Example code

```
try
    # code that may throw an error
catch err
    # code to handle the error
end
```

## Output example

```
No output
```

## Code explanation

1. `try`: This is the start of the try-catch block. All code that may throw an error should be placed between the `try` and `catch` keywords.
2. `catch err`: This is the start of the catch block. The `err` variable is used to store the error that was thrown.
3. `end`: This is the end of the try-catch block.

## Helpful links
1. [JuliaLang Documentation - Error Handling](https://docs.julialang.org/en/v1/manual/control-flow/#Error-Handling-1)

onelinerhub: [How to use try catch in JuliaLang?](https://onelinerhub.com/julialang/how-to-use-try-catch-in-julialang)